INSERT INTO PRODUCT_TYPE (ID, TYPE, TYPE_DISPLAY_NAME) VALUES (1, 'SMTV', 'Smart TVs');
INSERT INTO PRODUCT_TYPE (ID, TYPE, TYPE_DISPLAY_NAME) VALUES (2, 'APPL', 'Kitchen Appliances');
INSERT INTO PRODUCT_TYPE (ID, TYPE, TYPE_DISPLAY_NAME) VALUES (3, 'PHON', 'Smartphones');
INSERT INTO PRODUCT_TYPE (ID, TYPE, TYPE_DISPLAY_NAME) VALUES (4, 'AUDI', 'Audio Visual Devices');
INSERT INTO PRODUCT_TYPE (ID, TYPE, TYPE_DISPLAY_NAME) VALUES (5, 'HOME', 'Home Appliances');