INSERT INTO PRODUCT_TYPE (ID, TYPE, TYPE_DISPLAY_NAME) VALUES (1, 'SMTV', 'Smart TVs');
INSERT INTO PRODUCT_TYPE (ID, TYPE, TYPE_DISPLAY_NAME) VALUES (2, 'APPL', 'Kitchen Appliances');
INSERT INTO PRODUCT_TYPE (ID, TYPE, TYPE_DISPLAY_NAME) VALUES (3, 'PHON', 'Smartphones');
INSERT INTO PRODUCT_TYPE (ID, TYPE, TYPE_DISPLAY_NAME) VALUES (4, 'AUDI', 'Audio Visual Devices');
INSERT INTO PRODUCT_TYPE (ID, TYPE, TYPE_DISPLAY_NAME) VALUES (5, 'HOME', 'Home Appliances');

INSERT INTO PRODUCT (ID, PRODUCT_TYPE_ID, CODE, DEFAULT_DISPLAY_NAME, STATUS)
    VALUES (1, 1, 'SAMSUNG_TV_01_BLACK', 'Samsung Smart TV Black', 'ACTIVE');

INSERT INTO PRODUCT_DISPLAY_NAME (ID, PRODUCT_ID, LOCALE, DISPLAY_NAME)
    VALUES (1, 1, 'EN', 'Samsung Smart TV Black');

INSERT INTO PRODUCT_PRICE (ID, PRODUCT_ID, CURRENCY, PRICE, START_DATE_TIME, END_DATE_TIME)
    VALUES (1, 1, 'HKD', 5000, '2023-05-01 00:00:00',
    '2023-08-31 23:59:59');